### ISSUE TITLE
Get altitude from pressure

### ISSUE THREAD

**Issue by stephane-21** [airinnova/ambiance#4]
Hello,
Sorry if my question is not at the right place.
This can also maybe be seen as a feature request.

I have looked at the documentation, was wondering if there is a way to get ICAO values from a given air pressure.
`>>> from ambiance import Atmosphere`
`>>> icao_atmo = Atmosphere(pressure=50000)`
`>>> icao_atmo.altitude`

That would be like to simulate a not calibrated altimeter of an aircraft, from the measurement of the true pressure, it tells you the pressure altitude.
Or am I supposed to do an interpolation from vectors ?

Thanks in advance,

**Comment by aarondettmann** [comment]
Hello Stephane,

Thanks for the feature request. I can certainly see the use case for this, and I think it is a good idea. That said, I will probably not work on this in the near future myself. I am happy to accept pull requests, if you would like to work on this.

In your case, the simplest solution might just be to create a static table with altitude and pressure, and then to simply linearly interpolate with your own function.

If this feature is added to this package as a built-in option, I would currently be inclined to implement this with a `@classmethod`. In dummy code this would looks something like this:

```python
class Atmosphere

    ...

    @classmethod
    def from_pressure(cls, p):
        """Return an atmosphere instance from given pressure"""

        h = pressure2altitude(p)
        return cls(h)
```

However, one has to think a little about the function `pressure2altitude()`. The pressure function is a little tricky since it has different definitions for different values of beta which are altitude dependent. With the above implementation, an atmosphere object can be instatiated with a new constructor method.

```python
atmos = Atmosphere.from_pressure(50000)
atmos.h  # Geometric altitude
atmos.H  # Geopotential altitude
atmos.temperature  # Ambient temperature
...
```

The following questions should also be considered:

* Should vectors/matrices be accepted as input?
* Should we allow similar methods for other properties, say temperature? Note that temperature values are not unique. There can be two or three altitudes with same temperature.

**Comment by aarondettmann** [comment]
I thought about your suggestion a little more. One very simple way to get the altitude is to just use a [bisection method](https://en.wikipedia.org/wiki/Bisection_method). This probably not the most efficient way but is seems to be quite robust. I have updated this package.

Perhaps it helps you out a little. If have added some basic tests for this. If you want, you may try it yourself, and see if it is accurate enough. Currently only single pressure values are allowed as inputs. The method could be improved to allow for vectors or matrices as inputs.

* See [documentation](https://ambiance.readthedocs.io/en/latest/user_guide/detailed_user_guide.html#instantiating-from-given-pressure)

To update your installation of ``ambiance`` you can run one of the following commands depending on your installation:

```
pip install --upgrade ambiance
pip install --upgrade --user ambiance
```

**Comment by aarondettmann** [comment]
At a second glance at the _SciPy_ documentation, the [Newton method](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.newton.html) seems to be more powerful than the bisection. It also allows you to check multiple pressure values at once. Usage examples:

```python
>>> from ambiance import Atmosphere

>>> Atmosphere.from_pressure(1e5).h
array([110.88636257])  # in metres

>>> atmos = Atmosphere.from_pressure([1e5, 1e3, 1e1])
>>> atmos.h
array([  110.88636257, 31207.06116863, 65617.3058236 ])
>>> atmos.temperature
array([287.42925122, 227.70460582, 231.59869206])
```

I will mark this issue as closed. But feel free to comment if you have any other questions or remarks.

**Comment by stephane-21** [comment]
Sorry I didn't have time until now to answer to your message,
Moreover I have never used this "@classmethod" stuff.
And thanks a lot for the code modification.

On my side, the solution I chose is to generate a static table with 100 points :
`altitude_list = list(numpy.linspace(ICAO_LOWER_LIMIT, ICAO_UPPER_LIMIT, num=100))`
This table is generated once at each execution of my program, so for one table generation the table will be used several times.
After that first generation of the static table, only an interpolation function is used :
`scipy.interpolate.interp1d(pressure_list, altitude_list, kind='cubic')`
With my use case, that's the way which minimize the CPU usage with a reasonable medium accuracy.

I think that the approach I have used is probably not applicable to the ambiance package usage philosophy because you would have to regenerate the static table at each request, here theoretically the Newton interpolation method gives more accurate values for the same CPU time.

Nevertheless, after having tested your code v1.02, it looks like the usage of "from_pressure" is still very fast and with a high accuracy of ~ 10**-16.
So I will probably abandon my own code (static table) and switch to that new 1.02 "from_pressure" usage.

**Comment by nikiexpo** [comment]
Hey, I haven't really used this module but I was looking into this repo while writing code for my own implementation of pressure-to-altitude conversion in C++, I was wondering why the Newton method was chosen instead of just rearranging the math equation found in the standard. I implemented it that way and my output is somewhat close to the output from this module (within 2%). I am not critiquing the devs, I am just curious as to why that way was chosen and if there were any advantages to that method.

$\text{if}  \beta \neq 0$
 $$H = H_b + \frac{T_b}{\beta} ((\frac{P_b}{P})^{\frac{\beta R}{g_0}} - 1)$$
$\text{if}  \beta = 0$ 
$$H = H_b + \frac{RT}{g_0} ln({\frac{P_b}{P}})$$

Layer constants were dealt with by another function that checks the pressure and checks against the base pressure and picks the layer.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/85587378/217405965-a4353050-8c50-41b8-8327-b52a3a2cdca1.png">

This is the plot I get (the pressure below is sea-level is attenuated as I don't need it for my use case).

**Comment by aarondettmann** [comment]
Hello @nikiexpo, thanks for the question. Yes, I see no problem with your approach. The main reason for choosing the Newton method was the fairly simple implementation and the generality of this approach (SciPy's Newton method works with scalar values, vectors, and matrices. And, the method can be applied to other quantities too [1] without much thinking). If performance is an important factor for you, it may not be the ideal approach.

[1] `from_density()` is implemented analogous to `from_pressure()`:

https://github.com/airinnova/ambiance/blob/232032bbac7a8ff12e8bf9e888f6179d9094b0e9/src/ambiance/ambiance.py#L267-L283

I am happy to look at pull requests for any improvements to this package.
