### ISSUE TITLE
.from_pressure() bounds

### ISSUE THREAD

**Issue by stephane-21** [airinnova/ambiance#5]
With the 1.02 version, have been added the new feature ".from_pressure()"

I have noticed that at line 260 of "master/src/ambiance/ambiance.py" you are using hard-coded approximate values for atmo pressure bounds.

This will provoke the following code to crash :
`from ambiance import Atmosphere`
`height_amsl = 81000`
`icao_atmosphere = Atmosphere(height_amsl)`
`pressure = icao_atmosphere.pressure[0]`
`pressure`
`height_amsl_2 = Atmosphere.from_pressure(pressure).h[0]`
`height_amsl_2`

Instead, maybe you should generate these 2 bounds pressure values from "CONST.h_min" and "CONST.h_max".
But that will probably lead to other problems with the "scipy.optimize.newton()" algorithm which doesn't seem to accept interval.
When searching for a zero of f(ht) too close to the true exact bounds, it will raise an other exception.
The algo "scipy.optimize.bisect()" used with the version v1.01 had the advantage to consider an interval.

(I know that these issue is really about perfectionism. I don't even know if 81km is part of ICAO, but I have noticed this value h_max= 81020m into the code, maybe that's already a margin that you considered on the very same subject ?)

**Comment by aarondettmann** [comment]
Hi Stephane,

Thanks for your [feedback](https://github.com/airinnova/ambiance/issues/4#issuecomment-696030181) and thorough testing.

Yes, I am aware that the current implementation is not perfect and it will fail at the boundaries. I suppose this could be fixed by modifying the function `f()` which is passed to `scipy.optimize.newton()`. Or perhaps, there is a better method altogether. I switched from `bisection()` to `newton()` because it seemed to perform faster and because vectors/matrices can be passed in as argument to the `newton()` method.

I was thinking that the use case for the `from_pressure()` method would be to get the altitude from some static pressure measurement in a balloon or aircraft. Neither will/can fly close to the boundaries of this particular atmospheric model. But, yes, it it not a perfect implementation.

Improvement suggestions to the code are welcome :)

**Comment by aarondettmann** [comment]
I have added a fix for this issue (currently on a development branch, but I will probably merge sometime in the next days and then also update the PyPi package).

Basically, I allow the Newton method to get "out-of-bounds" while trying to find a solution. To do so, I added an extra argument called `check_bounds` which, if `False` allows heights outside the range `[CONST.h_min, CONST.h_max]`. Below, I have plotted the pressure from -10km to 100km.

```python
import numpy as np
import matplotlib.pyplot as plt
from ambiance import Atmosphere

# Make an atmosphere object
heights = np.linspace(-10e3, 100e3, num=1000)
atmosphere = Atmosphere(heights, check_bounds=False)

# Make plot
plt.plot(atmosphere.pressure, heights/1000)
plt.ylabel('Height [km]')
plt.xlabel('Pressure [Pa]')
plt.xscale('log')
plt.grid()
plt.show()

print(atmosphere.pressure[0])
print(atmosphere.pressure[-1])
```

![pressure](https://user-images.githubusercontent.com/42786424/93809579-ba823c00-fc4d-11ea-888a-529227dee7c0.png)

```
295587.36790765345
0.025455644112646402
```

See improved implementation:

https://github.com/airinnova/ambiance/blob/112d588e33e32149a14f4c554b6b0cf08a847ddb/src/ambiance/ambiance.py#L242

Now, your code does not crash:

```python
>>> from ambiance import Atmosphere
>>> height_amsl = 81000
>>> icao_atmosphere = Atmosphere(height_amsl)
>>> pressure = icao_atmosphere.pressure[0]
>>> pressure
0.8892236916312535
>>> height_amsl_2 = Atmosphere.from_pressure(pressure).h[0]
>>> height_amsl_2
81000.0
>>>
```

**Comment by aarondettmann** [comment]
The PyPi package is now updated. Note that I changed the function for the Newton method from


```python
def f(ht):
    return p - cls(ht, check_bounds=False).pressure
```

to

```python
def f(ht):
    return np.log(p/cls(ht, check_bounds=False).pressure)
```

This log-function still has the same root, but it's more or less a straight line (see plot above), and the Newton method requires fewer iterations to find a solution, so it is a bit faster.
