### ISSUE TITLE
conda install fails due to hard requirements

### ISSUE THREAD

**Issue by MarkusZimmerDLR** [airinnova/ambiance#9]
The conda package installation fails due to following hard requirements:
```
  - adjusttext==0.7
  - h5py==3.2
  - hdf4==4.2
  - hdf5==1.10
  - ipopt==3.13
  - matplotlib==3.4
  - pyqt==5.12
  - pyvista==0.28
  - qt==5.12
  - tabulate==0.8
```

Maybe those can be softened using a `>=`.
Otherwise the package will only work in its own environment and may not be integrated into others.

**Comment by aarondettmann** [comment]
Hello @MarkusZimmerDLR ,

Thanks for the report. As this is nearly a year old, I guess that it is probably not very relevant anymore, so I am closing here.

Otherwise, feel free to reopen the report (I will try to look into the issue relatively soon in that case). Consider reopening the issue here instead: https://github.com/conda-forge/ambiance-feedstock (build repository for the Conda package). And if you do, could you please give more detailed instructions on how to repeat the error?

None of the packages that you mention are any hard requirements of the **ambiance** package itself. At least the PyPi package only requires numpy and scipy with unspecified version numbers, see:

 https://github.com/airinnova/ambiance/blob/da7f2b265560ad79084ef740d9802870bb00b36b/setup.py#L22

(Scipy could be made optional even.)

I have to admit I am not really familiar with the Conda ecosystem, and I did not create the Conda package in the first place. So possibly, dependencies are handles differently there.

Kind regards.
